### ISSUE TITLE
Restyle front end prettier

### ISSUE THREAD

**Issue by abbeyjackson** [CodersWithoutBordersTech/refugee-lawyers#14]

**Comment by renatomcamilio** [comment]
@abbeyjackson would you mind helping me by listing some actionable items? I have the toolbox, but I need some guidelines, some sort of target; Prettier is "pretty" vague.

@98chimp maybe you can help us on this, just putting together a drawing with information?! Also, can we list what are we missing for this landing page?  

I guess these sections would be good:
 - [x] Header, navigation bar with links for the sections, and logo?! 
 ~Intro, motivation?! (needs content)~
 - [x] Lawyers list
 - [x] Footer, using CWB copyright?! + links

After getting a better idea on the target, I can turn these ^ items into tasks in the Project.

**Comment by abbeyjackson** [comment]
@renatomcamilio Oh I just made this issue because I saw you and @98chimp talking about doing something more later.  So I made an issue for it for you guys.

**Comment by renatomcamilio** [comment]
Oh, sounds good. We can talk about it later then. Ty!

**Comment by 98chimp** [comment]
guys, i don't believe this project requires too much elaboration
what i envisioned for this page is a very minimalistic design with just a title and the list that visitors will scroll through (at least for now)... my anxiety is that every day we wait building this thing is a day longer for someone stranded at one of the airports to have to stay there. 
we can certainly add a logo to the top left and a copyright statement in the footer along with a contact email.

**Comment by 98chimp** [comment]
we don't yet have an email service for the domain, but even the chosen name is under some scrutiny at the moment.
so let's reach a consensus on the name so that I can set up temp email addresses for us and finalize that page

**Comment by renatomcamilio** [comment]
@98chimp I think I misunderstood the issue title; AFAICT @abbeyjackson only intended to do a reminder so we wouldn't lose track of it.

**Comment by abbeyjackson** [comment]
@98chimp @renatomcamilio yes that was exactly it. I just am trained at work that everything you do you make an issue lol Sorry!

**Comment by renatomcamilio** [comment]
Closing since we've achieved the restyle task; Will create a proper issue for future items.
