### ISSUE TITLE
Template introduction letter to groups asking for their lawyer contacts

### ISSUE THREAD

**Issue by abbeyjackson** [CodersWithoutBordersTech/refugee-lawyers#5]
Letter: https://drive.google.com/open?id=10RuzhQXwbMXFH2JD1BAT0XQpCTnwy9OgyX_YMPHbbfg

**Comment by northtwilight** [comment]
2 letters:
https://docs.google.com/document/d/10RuzhQXwbMXFH2JD1BAT0XQpCTnwy9OgyX_YMPHbbfg/edit
https://docs.google.com/document/d/16rxcWlmPDbZovHacjV2o1DnZqindKNObjObIn4K7vZ4/edit
