### ISSUE TITLE
Website - data

### ISSUE THREAD

**Issue by abbeyjackson** [CodersWithoutBordersTech/refugee-lawyers#8]
How will the data be stored, edited and accessed? Plan and execute

**Comment by renatomcamilio** [comment]
@abbeyjackson my initial idea is to have a JSON in the repo, and you can easily edit through GitHub. Still figuring out with @98chimp, we are going to keep you guys in the loop.

**Comment by renatomcamilio** [comment]
Did put into a JSON file living in the repo here: https://github.com/CodersWithoutBordersTech/refugee-lawyers/blob/master/lawyers.json

If you edit the JSON directly on GH, it will reflect right away in prod! (At least should, unless GH heavy caches our data, which shouldn't be the case)
