### ISSUE TITLE
Website - hosting

### ISSUE THREAD

**Issue by abbeyjackson** [CodersWithoutBordersTech/refugee-lawyers#9]
Hook up hosting to get the website public facing, idea: github website hosting

**Comment by renatomcamilio** [comment]
@98chimp let me know when you have the HTML ready. If you have a sketch I can put it together myself.

**Comment by renatomcamilio** [comment]
Closing this one since we've agreed to host it on GH Pages. I'll be working close to @98chimp on the page & hosting.
